/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getDisplayName' : IDL.Func([], [IDL.Text], ['query']),
  'getLikedSongs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isSongLiked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'toggleSongLike' : IDL.Func([IDL.Text], [], []),
  'unlikeSong' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getDisplayName' : IDL.Func([], [IDL.Text], ['query']),
    'getLikedSongs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isSongLiked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'toggleSongLike' : IDL.Func([IDL.Text], [], []),
    'unlikeSong' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };